ALTER TABLE child_profiles ADD COLUMN grade_level INTEGER NOT NULL DEFAULT 0;
ALTER TABLE tracks ADD COLUMN subject TEXT NOT NULL DEFAULT 'math';
ALTER TABLE tracks ADD COLUMN grade_level INTEGER NOT NULL DEFAULT 0;
